language: node_js
node_js: [node, lts/*]
os: [linux, osx]
env:
  global:
    secure: v+1VHkeZysE+FGsNzh+Sw/dyJ/TjU8IoSoDDDN843bafVnUkUSD/qxlm5lfYYmelbWCQR9xl2HPSb0auitvusDXXTMPDil74D7JOeC0xSsK4jq68Ypc5Jb8jLkjZDI5URPcO8/AifUWuKK+NXMGpcFUP1r5qdIsPnTC1Hv7L561cXYXB3OdOOJmDYcX9UWWDRSZkfR54+qlfzydM57wfTOXS4tJ9Wj4oPyDkRi9KETzCtO1y1Q1Jn5tl1V4rYcT7T6upPb/Lboc9pGeGYqMVUg8NQbudjX9ZvKSyzssIQ/qSMrVL8JdwKwmOv3fH2ps4e+FflaUvwNyt4oohRYlWfMazdKhWuOozKslazj4Gf4m/Th40rFamgxL9psa1Z9rWoJ4/F4HgLt1wo4yzp1Zk/e3Ls2kyRS2mHtfO/MA8MQ8ZT6VIK+Xl7OVtD0Ijt00pNk+vO9Ii64Fp6orm26KgwKvAgl6xKdSUuPJz9c/v6T3zb315UKlmb/0CaCVQfJOu4orGfTXSWM6Hl9UTf0X+Ynk8WuZLm98AIODS+2bOxdSOwhakSHIIZWcDVOqi9ECO+CMy12ruAKQhDFp0KshubPdhT/CYkoDMtpNBVSckrXB/zpouCv9J1Qk67pZiu3lNoYCcOogbGp5GYumCPiSk5NDE8fb+zK0WIoWrRSgeUrA=
