language: node_js
node_js: [node, lts/*]
os: [linux, osx, windows]
cache:
  npm: true
jobs:
  include:
  - stage: Deploy
    before_deploy:
    - zip -9 -r bundle.zip dist
    - ./node_modules/.bin/rimraf "dist/readme.*" "dist/**/*.d.ts" "dist/**/*.map"
    - zip -9 -r bundle-min.zip dist
    deploy:
    - provider: pages
      local-dir: dist-jsdoc/html
      fqdn: array-to-object-keys.jaid.codes
      skip-cleanup: true
      github-token: $GITHUB_TOKEN # Permissions: public_repo, repo:status, repo_deployment
    - provider: releases
      files:
      - bundle.zip
      - bundle-min.zip
      skip-cleanup: true
      api-key: $GITHUB_TOKEN # Permissions: public_repo, repo:status, repo_deployment
      on: { tags: true }