language: node_js
node_js:
- node
- lts/*
os:
- linux
- osx
env:
  global:
  - secure: "iwwnswUS4TAGOl8adXlNXUiRfirywxHj52qK25wxZeUENyE1Y3Jrm85sWuGOW8yATSqpVZ2IIMx2mcd4oUIImAlUVX0gminsVjVBlAnNk2uDqUxs2DBuPOmCpjY8Ggy/mdbtKGT8bGvvz8eMcg93INJTuIaHj/l9VpwNoNmKGzyae3sGnKxuFfOtI+z/JiO+sA2T+JHmad691y3rw1JIDL+oJ+tazRnaujd23m8V/pUx+52gJepy2N3TXASa0Hm2BoTzN1WR/nT4zhePuEu3eoEfM7UB8rU5T3b7uyfMzr4+dM3jB8+vkf7u4snQbn6NGBwgozE5tBHCt6XECX+OwCl4oVvdRHBrrPy9sR8DcUN+NuAbV5eseCfaKA8IL+xgqb4hs0tPFUJNSk+08iBUYH86qJ0dmL5WpO0BShTBaEr+zShxnc5jv/sZImbSVVkxwhGZNQWZ62o06aBJWHyfA2detAfzwH9XFyh1Y9lzKCYV8qADEf6VsZQrFCepR9dM03wXd9bHYh9cmyGmTq0fdYcTl1aqgvHki847bvwSUL+l/YFXnhqokQ6TifE/OGe6nwKUGuTonsC11XGyXU/qe0kLesPuqyIjR6vuyC+k2b7wu3KCitoWATxpiw2/VSgq0X9L0FyDsI0BGu6kUUwpOTFdZsk0Tq47/jL+mKW1Z+I="
script:
- node -e "console.log(JSON.stringify(process.env))"