language: node_js
node_js: [node, lts/*]
os: [linux, osx] # Windows doesn't work currently, I should try again in May 2019
cache:
  npm: true
jobs:
  include:
  - stage: Deploy
    before_deploy:
    - export MY_PACKAGE_NAME=$(node -e "console.log(require(\"./dist/package\").name)")
    - export MY_PACKAGE_VERSION=$(node -e "console.log(require(\"./dist/package\").version)")
    - zip -9 -r $MY_PACKAGE_NAME-v$MY_PACKAGE_VERSION.zip dist
    - ./node_modules/.bin/rimraf "dist/readme.*" "dist/**/*.d.ts" "dist/**/*.map"
    - zip -9 -r $MY_PACKAGE_NAME-v$MY_PACKAGE_VERSION-min.zip dist
    deploy:
    - provider: pages
      local-dir: dist-jsdoc/html
      fqdn: $MY_PACKAGE_NAME.jaid.codes
      skip-cleanup: true
      github-token: $GITHUB_TOKEN # Permissions: public_repo, repo:status, repo_deployment
    - provider: releases
      files:
      - $MY_PACKAGE_NAME-v$MY_PACKAGE_VERSION.zip
      - $MY_PACKAGE_NAME-v$MY_PACKAGE_VERSION-min.zip
      skip-cleanup: true
      api-key: $GITHUB_TOKEN # Permissions: public_repo, repo:status, repo_deployment
      on: { tags: true }