language: node_js
node_js: [node, lts/*]
cache:
  npm: true
script:
  - npx pover install
  - npx pover build:dev
  - npx pover build:prod
  - npx pover test
jobs:
  include:
    - stage: Deploy
      before_deploy:
        - npm run build:prod
        - npx compile-release
      deploy:
        - provider: pages
          local_dir: page
          fqdn: $PKG_NAME.jaid.codes
          skip_cleanup: true
          github_token: $GITHUB_TOKEN # Permissions: public_repo, repo:status, repo_deployment
          on: { condition: -d pages }
        - provider: releases
          file_glob: true
          file: dist/github/*
          skip_cleanup: true
          api_key: $GITHUB_TOKEN # Permissions: public_repo, repo:status, repo_deployment
          on: { tags: true }
        - provider: script
          script: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && npm publish dist/package/production
          skip_cleanup: true
          on: { tags: true }
