language: node_js
node_js:
- node
- lts/*
os:
- linux
- osx
env:
  global:
  - secure: JYnZYWYKL0wItxj9/Ekl67yb0JG67o909QYOERzJBPrtoaMeW0W23QxiHK2OhRbejvdtIMT/eI/4pdIj/DG3cbsvn+P12lHHjBss+xG0ndqX8VosqKamslRO/qMY1mrfXGld0U/s3O8FbHXHBks8poQ1NGRDzJejDTuQMvmkhBZvtaCUcDvqZLuwI5rp2L01uW5PJvKuPnxv6LwaHjnk31RPCoOfRNCmUP1nNd6PsmdUDc0kVNsM7Do8HhrXh9j/YENfD1OpyaDCr6wkn5i0XoRczDi0ighztePOvFhpKBZm8XZ0oeR6Fkxo5afIfLG5DimEmBnF78pwB71j6rxikvhkLt1j0ucG2gooDUjKFyAR3/8KBwxD9o4TqudWrCU6jCmbmyXkGVEJdG99Fy1R/rSQkUlYvUXvx/hfl+Kjx1iOLqM2BvN+v1NbXIHK7rST803RL9wOhF9E4ft8xiwVBSd0qOnsAObFTq0NVl6n8uCHpCOrkiovZRh8jEdoNQRy+6oianBUFSXsFWYqbWxIADs2R9YDsW42mkA5b2HsPXF7LV3D+gMX6z8M8vfcUSqR/ou6q2XTToKUQgUiUtEAyzNo6A1fwY9hAXvLoUB7ZJCSzCqSNaeold+a7cIFK/ktENtoZ7i1Q2oIvD2gUz3nEBKJu/m6yyPh0YXdq94Th2E=
