language: node_js
node_js: [node, lts/*]
os: [linux, osx]
env:
  global:
  - secure: Dsd+mhFawopmq0l5tiRldy3f6rdFXyIjAXB2i3x3cUFMDPP8DRuWzy21gYkN8Uw5Y7iuEwBALaP3Qh4hXiOSEhXrVH5cAnKIeIXaiAZoXtYJXopQVu7bSSvZN7FziwclCnM3NhtQDznhuTjyXv4C2hLhrCY2DHN53DdUMym0+58jpJ5lfb8bn6iEC+CxSYE7kkHho2GEYdDun0BsUQQj2tq0XHLcBOtpGhkjr5RbnWyjivA8Nn3WS+Y/EUk1cYLTvN77WlegXCmeI0S2bHsrF0QeHiwK7VObf7oeQBS6+ScNc845mwEszEjdG35jl+eiTbIskYOZNQFEFZ645xPSaTE8CRhYU1zCb0wOfBZyoiYJTK8sp7S6M2deayN4KBsjETPC2SjYmSp3L2fNB0U9hP9eIl48eqXDqasjlYB484dPyX69g7QIpcFxFcIu395aPOJ/hL4c09s/XH3p8Uh3pBEJgG6pM09mW9ww2jHOuH2Cc2C1ntKHYy/bKv91kc6swjjckA2Ea9DerRP5ooAaDuC5yoVI8B+DU6P+N3JodlHRG9phMhXO0thGAwSGh6RX6C2qpuZHvyNkpv4r2J6Q/MqoQjrfMofSxnA0j9VnrpKXZnA+3NOkoxdPXhy2XQ1VkViaQXhk9yJ1nt9tjpc0yCzrsZN29N6SB0z9WS6tc6s=
